version: '3'
services:
  app:
    build:
      context: ./php
    volumes:
      - './../:/var/www/html'
      - './data/sites:/etc/apache2/sites-available'
      - './data/LOGS:/var/www/logs'
      - './data/root:/root'
      - './sql:/home/sql'
    links:
      - db
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.0.99
  db:
    image: mariadb
    volumes:
      - './base:/var/lib/mysql'
      - './sql:/home/sql'
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      app_net:
        ipv4_address: 172.16.0.98

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      app_net:
        ipv4_address: 172.16.0.97

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
